server:
  port: 8081

# 多数据源路由配置
mini-db-router:
  jdbc:
    datasource:
      dbCount: 3
      tbCount: 3
      default: db00
      routerKey: uId
      list: db01,db02,db03
      db00:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mylottery?useUnicode=true
        username: chenxinli
        password: jpxx1724
      db01:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery_01?useUnicode=true
        username: chenxinli
        password: jpxx1724
      db02:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery_02?useUnicode=true
        username: chenxinli
        password: jpxx1724
      db03:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/lottery_03?useUnicode=true
          username: chenxinli
          password: jpxx1724

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Dubbo zookeeper注册中心方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: fr.utc.mylottery.rpc


